version: '3'

services:
  db:
    image: mysql:8.0.12
    container_name: joguin_db
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: The|r00t_82
      MYSQL_DATABASE: joguin
      MYSQL_USER: jogador
      MYSQL_PASSWORD: The|j0g@d0r_18
